version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - APP_PORT=8080
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=clean_arch_go
      - REDIS_ADDR=redis:6379
      - JWT_SECRET=your-jwt-secret
      - JWT_EXPIRATION_MINUTE=1440
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
    command: sh -c "go run cmd/api/main.go"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clean_arch_go
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
